In [7]:
import pandas as pd
import numpy as np
import requests
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import json
import re
import random
import lxml

## Context ##

As an avid fan, I love following my team, but also players from all other teams. However, advanced stats are not only hard to come by, but they're quite hard to read. I want to create a way to quantify the data to grade and rank players across numerous metrics, to look beyond goals and points. There are many models out there like the WAR model, but those are readily available to the public. My goal with this projet is to create something similiar, but publish it for all fans to enjoy and learn.

### Public Sources to Use ###
https://www.naturalstattrick.com/

https://moneypuck.com/stats.htm

https://hockeyviz.com/team/S.J/2425

In [8]:
url = "https://www.naturalstattrick.com/playerteams.php?fromseason=20242025&thruseason=20242025&stype=2&sit=5v5&score=all&stdoi=oi&rate=n&team=ALL&pos=S&loc=B&toi=0&gpfilt=none&fd=&td=&tgp=410&lines=single&draftteam=ALL"
tables = pd.read_html(url)
df = tables[0]

In [11]:
df.head()

,Unnamed: 0,Player,Team,Position,GP,TOI,CF,CA,CF%,FF,...,PDO,Off. Zone Starts,Neu. Zone Starts,Def. Zone Starts,On The Fly Starts,Off. Zone Start %,Off. Zone Faceoffs,Neu. Zone Faceoffs,Def. Zone Faceoffs,Off. Zone Faceoff %
0,1,Ryan Suter,STL,D,82,1396.866667,1185,1394,45.95,823,...,1.017,147,312,187,1085,44.01,321,457,419,43.38
1,2,Brent Burns,CAR,D,82,1293.400000,1590,1159,57.84,1119,...,0.982,227,245,160,935,58.66,507,400,418,54.81
2,3,Corey Perry,EDM,R,80,828.516667,881,739,54.38,611,...,1.013,183,141,76,609,70.66,302,193,167,64.39
3,4,Alex Ovechkin,WSH,L,65,822.200000,815,859,48.69,596,...,1.045,242,185,23,639,91.32,392,229,98,80.00
4,5,Evgeni Malkin,PIT,C,68,981.550000,984,992,49.80,690,...,0.990,179,224,58,803,75.53,347,335,185,65.23

In [12]:
df.shape

(920, 54)

In [17]:
# Check to see if there are any null values for any player in the table (THERE AREN'T)
null_check = df.isnull().sum()
null_check

Unnamed: 0             0
Player                 0
Team                   0
Position               0
GP                     0
TOI                    0
CF                     0
CA                     0
CF%                    0
FF                     0
FA                     0
FF%                    0
SF                     0
SA                     0
SF%                    0
GF                     0
GA                     0
GF%                    0
xGF                    0
xGA                    0
xGF%                   0
SCF                    0
SCA                    0
SCF%                   0
HDCF                   0
HDCA                   0
HDCF%                  0
HDGF                   0
HDGA                   0
HDGF%                  0
MDCF                   0
MDCA                   0
MDCF%                  0
MDGF                   0
MDGA                   0
MDGF%                  0
LDCF                   0
LDCA                   0
LDCF%                  0
LDGF                   0
LDGA                   0
LDGF%                  0
On-Ice SH%             0
On-Ice SV%             0
PDO                    0
Off. Zone Starts       0
Neu. Zone Starts       0
Def. Zone Starts       0
On The Fly Starts      0
Off. Zone Start %      0
Off. Zone Faceoffs     0
Neu. Zone Faceoffs     0
Def. Zone Faceoffs     0
Off. Zone Faceoff %    0
dtype: int64